"use client";

import { getClientTimeZone } from "@/lib/local-dates";

function urlBase64ToUint8Array(base64String: string) {
  const padding = "=".repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, "+").replace(/_/g, "/");
  const rawData = window.atob(base64);
  return Uint8Array.from([...rawData].map((char) => char.charCodeAt(0)));
}

function arrayBufferToBase64Url(value?: ArrayBuffer | null) {
  if (!value) return "";
  const bytes = new Uint8Array(value);
  let binary = "";
  bytes.forEach((byte) => {
    binary += String.fromCharCode(byte);
  });
  return window.btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, "");
}

function validateVapidPublicKey(publicKey: string) {
  try {
    const decoded = urlBase64ToUint8Array(publicKey.trim());
    if (decoded.length !== 65 || decoded[0] !== 4) {
      throw new Error("invalid key");
    }
    return decoded;
  } catch {
    throw new Error("Push notifications are misconfigured: NEXT_PUBLIC_VAPID_PUBLIC_KEY must be the VAPID Public Key generated by web-push.");
  }
}

export function supportsPushNotifications() {
  return typeof window !== "undefined"
    && "serviceWorker" in navigator
    && "PushManager" in window
    && "Notification" in window;
}

export async function registerPushNotifications() {
  if (!supportsPushNotifications()) {
    throw new Error("Push notifications are not supported on this device/browser.");
  }

  const stateRes = await fetch("/api/push/subscription");
  const state = await stateRes.json();
  if (!stateRes.ok) throw new Error(state?.error ?? "Could not load push settings");
  if (!state?.configured || !state?.publicKey) {
    throw new Error("Push notifications are not configured on the server yet.");
  }

  const permission = await Notification.requestPermission();
  if (permission !== "granted") {
    throw new Error("Notification permission was not granted.");
  }

  const registration = await navigator.serviceWorker.register("/sw.js");
  await navigator.serviceWorker.ready;
  await registration.update().catch(() => null);

  const applicationServerKey = validateVapidPublicKey(state.publicKey);
  let existing = await registration.pushManager.getSubscription();
  const existingKey = arrayBufferToBase64Url(existing?.options?.applicationServerKey);
  const expectedKey = state.publicKey.trim();

  if (existing && existingKey && existingKey !== expectedKey) {
    await fetch("/api/push/subscription", {
      method: "DELETE",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ endpoint: existing.endpoint }),
    }).catch(() => null);
    await existing.unsubscribe().catch(() => null);
    existing = null;
  }

  const subscription = existing ?? await registration.pushManager.subscribe({
    userVisibleOnly: true,
    applicationServerKey,
  });

  const saveRes = await fetch("/api/push/subscription", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      ...subscription.toJSON(),
      timeZone: getClientTimeZone(),
    }),
  });
  const saveData = await saveRes.json().catch(() => ({}));
  if (!saveRes.ok) throw new Error(saveData?.error ?? "Could not save push subscription");
  return saveData;
}

export async function getPushDeviceDiagnostics() {
  if (!supportsPushNotifications()) {
    return {
      supported: false,
      permission: "unsupported",
      controlled: false,
      subscribed: false,
      endpoint: null,
      keyMatches: false,
    };
  }

  const registration = await navigator.serviceWorker.getRegistration("/sw.js");
  const subscription = await registration?.pushManager.getSubscription();
  const headers = subscription?.endpoint ? { "x-dayza-push-endpoint": subscription.endpoint } : undefined;
  const stateRes = await fetch("/api/push/subscription", { headers });
  const state = await stateRes.json().catch(() => ({}));
  const key = arrayBufferToBase64Url(subscription?.options?.applicationServerKey);
  return {
    supported: true,
    configured: Boolean(state?.configured),
    permission: Notification.permission,
    controlled: Boolean(navigator.serviceWorker.controller),
    subscribed: Boolean(subscription),
    endpoint: subscription?.endpoint ?? null,
    keyMatches: Boolean(subscription && state?.publicKey && key === String(state.publicKey).trim()),
    serverSubscribed: Boolean(state?.subscribed),
    serverSubscriptionId: state?.subscription?.id ?? null,
  };
}

export async function unregisterPushNotifications() {
  if (!supportsPushNotifications()) return;
  const registration = await navigator.serviceWorker.getRegistration("/sw.js");
  const subscription = await registration?.pushManager.getSubscription();
  if (subscription) {
    await fetch("/api/push/subscription", {
      method: "DELETE",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ endpoint: subscription.endpoint }),
    });
    await subscription.unsubscribe();
  } else {
    await fetch("/api/push/subscription", { method: "DELETE" });
  }
}
